# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community
# DataSourceProperties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  # ThymeleafProperties
  thymeleaf:
    cache: false
#  MailProperties
  mail:
    host: smtp.qq.com
    port: 465
    username: 1172029461@qq.com
    password: vvvgbupraosnbafb
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 1
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  data:
    elasticsearch:
      cluster-name: chen
      cluster-nodes: 127.0.0.1:9300
# MybatisProperties
mybatis:
  mapper-locations:  mapper/*.xml
  type-aliases-package: com.chen.community.entity
  configuration:
    useGeneratedKeys: true
    map-underscore-to-camel-case: true
 #logger
#logging:
#  level:
#    com:
#      chen:
#        community: debug
#  pattern:
#    console: "[%thread] %-5level %logger{36} -%msg%n"
#community
community:
  path:
    domain: http://localhost:8080
    upload: d:/StudyMaterials/A-JavaLearn/B-project/upload